services:
  - type: web
    name: habit-tracker-backend
    env: node
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: HANKO_API_URI
        sync: false
      - key: HANKO_TENANT_ID
        sync: false
      - key: HANKO_API_KEY
        sync: false
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        sync: false